-- CAMPEONATOS
INSERT INTO CAMPEONATO VALUES('LIGA 1 - CORONEL',2023,'CORONEL',10);
INSERT INTO CAMPEONATO VALUES('LIGA 1 - CLARITA',2024,'CLARITA',8);
INSERT INTO CAMPEONATO VALUES('LIGA 1 - MOVISTAR',2025,'MOVISTAR',18);
GO

SELECT * FROM CAMPEONATO;
GO


-- EQUIPOS
INSERT INTO EQUIPO VALUES('ALIANZA LIMA','FARFAN','BUNKER');
INSERT INTO EQUIPO VALUES('REAL MADRID','FLORENTINO','ESPAÑA');
INSERT INTO EQUIPO VALUES('MANCHESTER CITY','JALAN','INGLATERRA');
INSERT INTO EQUIPO VALUES('UNIVERSITARIO','CUTO','CHINCHA');
GO

SELECT * FROM EQUIPO;
GO

-- INSCRIPCION
INSERT INTO INSCRIPCION VALUES(1,1);
INSERT INTO INSCRIPCION VALUES(1,2);
INSERT INTO INSCRIPCION VALUES(1,3);
INSERT INTO INSCRIPCION VALUES(2,1);
INSERT INTO INSCRIPCION VALUES(2,2);
INSERT INTO INSCRIPCION VALUES(3,4);
INSERT INTO INSCRIPCION VALUES(3,3);
INSERT INTO INSCRIPCION VALUES(3,2);
INSERT INTO INSCRIPCION VALUES(3,4);
GO

SELECT * FROM INSCRIPCION;
GO


-- PAIS
INSERT INTO PAIS VALUES('PERU');
INSERT INTO PAIS VALUES('ARGENTINA');
INSERT INTO PAIS VALUES('COLOMBIA');
INSERT INTO PAIS VALUES('URUGUAY');
INSERT INTO PAIS VALUES('ECUADOR');
GO


-- JUGADORES
INSERT INTO JUGADOR VALUES(1,'JUAN PEREZ','LIMA',1);
INSERT INTO JUGADOR VALUES(1,'PEDRO COLCHADO','LIMA',1);
INSERT INTO JUGADOR VALUES(1,'JESUS TORRES','LIMA',1);
INSERT INTO JUGADOR VALUES(1,'CUBILLAS','LIMA',1);
INSERT INTO JUGADOR VALUES(1,'SOTIL','LIMA',1);
GO

INSERT INTO JUGADOR VALUES(5,'JUAN PEREZ','LIMA',1);
INSERT INTO JUGADOR VALUES(5,'PEDRO COLCHADO','LIMA',1);
INSERT INTO JUGADOR VALUES(5,'JESUS TORRES','LIMA',1);
INSERT INTO JUGADOR VALUES(5,'CUBILLAS','LIMA',1);
INSERT INTO JUGADOR VALUES(5,'SOTIL','LIMA',1);
GO

INSERT INTO JUGADOR VALUES(4,'CRISTIANO','LIMA',1);
INSERT INTO JUGADOR VALUES(4,'MESSI','LIMA',1);
INSERT INTO JUGADOR VALUES(4,'JALAN','LIMA',1);
INSERT INTO JUGADOR VALUES(4,'VINICIUS','LIMA',1);
INSERT INTO JUGADOR VALUES(4,'LUKAKU','LIMA',1);
GO

-- Consulta 1: Judaores del equipo 1 en el campeonato del 2023

select j.* 
from JUGADOR j
join INSCRIPCION i on j.IDINSCRIPCION = i.IDINSCRIPCION
join CAMPEONATO c on i.IDCAMPEONATO = c.IDCAMPEONATO
where i.IDEQUIPO = 1 and c.ANIO = 2024;
go


-- Consulta 2: En que equipos a participado el jugador SOTIL

select c.ANIO, e.NOMBRE 
from JUGADOR j
join INSCRIPCION i on j.IDINSCRIPCION = i.IDINSCRIPCION
join CAMPEONATO c on i.IDCAMPEONATO = c.IDCAMPEONATO
join EQUIPO E on i.IDEQUIPO = e.IDEQUIPO
where j.NOMBRE = 'CUBILLAS';
go





